export const COLORS = {
  brown: "color: brown",
  red: "color: red",
  green: "color: green",
  blue: "color: blue",
  yellow: "color: yellow",
  purple: "color: purple",
  cyan: "color: cyan",
  white: "color: white",
  black: "color: black",
  gray: "color: gray",
  orange: "color: orange",
  pink: "color: pink",
  violet: "color: violet",
  reset: "",
};
